services:
  - type: web
    name: litarcadewordle-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build --workspace=apps/api
    startCommand: npm run start --workspace=apps/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: ADMIN_SECRET_KEY
        sync: false
      - key: EVENT_TIMEZONE
        value: Asia/Kolkata
